feat: Enhance installation scripts with additional package checks and support for Snap and Neovim

diff --git a/run_onchange_before_nvim-plugin-checking.sh.tmpl b/run_onchange_before_nvim-plugin-checking.sh.tmpl
--- a/run_onchange_before_nvim-plugin-checking.sh.tmpl
+++ b/run_onchange_before_nvim-plugin-checking.sh.tmpl
@@ -12,14 +12,47 @@ HIGHLIGHT="\033[1;36m" # Cyan
 CMD="\033[1;90m"       # Gray
 SUCCESS="\033[1;92m"   # Bright Green
 
+function snapCheck(){
+  if ! command -v snap >/dev/null; then
+    echo -e "${WARNING}Snap is not installed. You need to install Snap first.${NC}"
+    echo -e "Please install Snap by running the following command:"
+    echo -e "${HIGHLIGHT}sudo apt update && sudo apt install snapd && sudo snap install core${NC}"
+    exit 1
+  fi
+}
+
 if ! command -v nvim >/dev/null; then
-  # TODO: Add instructions for installing Neovim on different Linux distributions, e.g. Ubuntu24.04, Ubuntu20.04, Kali, etc.
   echo -e "${WARNING}Neovim is not installed. Automatically installing Neovim...${NC}"
-  {{ if eq .chezmoi.os "darwin" -}}
-  cmd="brew install neovim"
-  {{ else if eq .chezmoi.os "linux" -}}
-  cmd="sudo apt install neovim -y"
-  {{ end -}}
-  echo -e "${CMD}$cmd${NC}"
-  eval $cmd
+  {{ if eq .chezmoi.os "darwin"}}
+  install_cmd="brew install"
+  {{ else if ( or 
+    ( eq .chezmoi.osRelease.id "ubuntu" )
+    ( eq .chezmoi.osRelease.id "debian" )
+    ( eq .chezmoi.osRelease.id "kali" )) }}
+  os_pretty_name="{{ .chezmoi.osRelease.prettyName }}"
+  case "$os_pretty_name" in
+      Ubuntu\ 22.04* | Ubuntu\ 22.10*)
+          snapCheck
+          install_cmd="sudo snap install nvim --classic"
+          ;;
+      *)
+          echo -e "${CMD}sudo apt update"
+          eval "sudo apt update"
+          echo -e "${NC}"
+          install_cmd="sudo apt-get install -qq -y neovim"
+          ;;
+  esac
+  {{ else if ( or 
+    ( eq .chezmoi.osRelease.id "arch" ) 
+    ( eq .chezmoi.osRelease.id "archarm" ) 
+    ( eq .chezmoi.osRelease.id "manjaro" )) }}
+  install_cmd="sudo pacman -S --noconfirm neovim"
+  {{ else }}
+  echo -e "${ERROR}Your OS is not supported. Please install Neovim manually.${NC}" 
+  echo -e "After installing Neovim, Re-run the script(${HIGHLIGHT}chezmoi apply${NC}) to continue installing the Neovim plugins."
+  exit 1
+  {{ end }}
+  echo -e "${CMD}$install_cmd"
+  eval "$install_cmd"
+  echo -e "${SUCCESS}Neovim has been installed successfully.${NC}"
 fi
